version: '3'

volumes:
  mongo_volume:
    driver: local

services:
  mongo:
    image: mongo
    container_name: mongo_example
    ports:
      - '27017:27017'

  # rabbit:
  #   image: rabbitmq:3-management
  #   container_name: rabbit_whitelabelbank
  #   ports:
  #     - '8080:15672'
  #     - '5672:5672'
  #     - '25676:25676'
